### ISSUE TITLE
rosconsole location being overwritten by class_loader

### ISSUE THREAD

**Issue by davetcoleman** [ros/rosconsole_bridge#5] opened 2014-02-18 11:31 UTC
I've spent ~1 hr trying to track down how this is happening, but I think someone more experienced with these low level libraries can help better.

In [bridge.cpp](https://github.com/ros/rosconsole_bridge/blob/hydro-devel/src/bridge.cpp#L109) line 109 it is setting the logger location (the "prefix") using:

```
ROSCONSOLE_DEFINE_LOCATION(true, ::ros::console::levels::Debug, prefix);
```

This works as expected for all logger levels (INFO, etc) except for DEBUG level, when using code in conjunction with class_loader library. By this I mean, if your code is loaded with class loader and you do this:

```
logError("foo: message")
```

You get something like:

```
ERROR ros.rosconsole_bridge.foo: message
```

But if you do the same thing with DEBUG:

```
logDebug("foo: message")
```

The prefix gets overwritten by classloader, and you get something like:

```
DEBUG ros.rosconsole_bridge.class_loader.class_loader_private: message
```

But searching through rosconsole, rosconsole_bridge and console_bridge I cannot figure out where its being overwritten. 

Note: this bug is likely an issue with a different repository, but I wasn't sure which one.

**Comment by isucan** [comment] 2014-03-21 04:03
Is this still an issue? If you have a fix for this, I'm happy to merge it.

**Comment by davetcoleman** [comment] 2014-03-21 06:17
It is still an issue, but it was a little over my head when I tried to fix it myself.

**Comment by davetcoleman** [comment] 2014-08-01 02:13
And... its still an issue. I can't see the debug output from moveit_planners_ompl because of this :-/

**Comment by dirk-thomas** [comment] 2014-08-01 19:19
Have you tried _Indigo_ and does it also have the same problem? If yes, can you please describe a simple-to-reproduce scenario?

**Comment by davetcoleman** [comment] 2014-08-03 23:34
I have not migrated to indigo (aside from testing on VMs) I'm afraid. I will do after summer collaboration in Japan is over.

**Comment by dirk-thomas** [comment] 2014-08-03 23:43
Can you please describe a simple-to-reproduce scenario - even if it on _Hydro_ only?

**Comment by davetcoleman** [comment] 2014-08-04 04:35
[Here](https://github.com/davetcoleman/rosconsole_test/blob/master/src/test.cpp) is an super simple example catkin package. Feel free to clone and build.

I think this is a good example of the problem I am having - it outputs to my terminal "Hello World" and shows the `logError` error message, but none of the messages after it. I have my rosconsole logger level set to simply:

```
log4j.logger=DEBUG
```

I also tried

```
log4j.logger.ros=DEBUG
```

Shouldn't I expect to see these inform and debug messages?

**Comment by dirk-thomas** [comment] 2014-08-04 07:25
Your example only uses `console_bridge` and not `rosconsole_bridge`.
Therefore your configuration file does not matter at all (since it is `rosconsole_bridge` specific).

The default log level of `console_bridge` is `warn` (https://github.com/ros/console_bridge/blob/b264091d223c396594a573e06aa63731cf694bce/src/console.cpp#L51).
Therefore the described output (only `error` and `warn`, not `inform` or `debug`) is what I would expect to happen.

**Comment by davetcoleman** [comment] 2014-08-04 08:13
So how do I change the `console_bridge` log level? Currently I have

```
export ROSCONSOLE_CONFIG_FILE=~/unix_settings/.my.rosconsole
```

which is where I have

```
log4j.logger=DEBUG
```

I couldn't find anywhere in RQT logger level to change this, either.

Perhaps this example is bad, but the problem I am experiencing is with moveit_core which does not use ROS_INFORM, etc but instead uses console_bridge

**Comment by dirk-thomas** [comment] 2014-08-04 15:28
`console_bridge` only allows you to change the log level programmatically. It does not support any kind of configuration file.

Please still provide an example which uses `rosconsole_bridge` and shows the problem you are having. Or describe any kind of scenario to reproduce.

**Comment by dirk-thomas** [comment] 2015-03-20 18:28
Without further information provided I will close this ticket for now. It can be reopened any time when a reproducible example is provided.

**Closed as completed by dirk-thomas** 2015-03-20 18:28 UTC
